FROM openjdk:17-oracle
LABEL authors="vangv"
COPY build/libs/public_store_service-0.0.1-SNAPSHOT.jar public_store_service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "public_store_service-0.0.1-SNAPSHOT.jar"]