spring:
  cloud:
    gateway:
      mvc:
        routes:
        #Public Access
          - id: public-store-service
            uri: http://192.168.160.1:9001
            predicates:
              - Path=/api/v1/public-store/
          - id: auth-admin-service
            uri: http://192.168.160.1:6001
            predicates:
              - Path=/api/v1/auth/admin/
          - id: auth-user-service
            uri: http://192.168.160.1:6002
            predicates:
              - Path=/api/v1/auth/user/
          #OAuth2
          - id: oauth-service
            uri: http://192.168.160.1:6003
            predicates:
              - Path=/**
          #Admin Service
          - id: admin-service
            uri: http://192.168.160.1:9002
            predicates:
              - Path=/api/v1/admins/
          #Admin Service
          - id: user-service
            uri: http://192.168.160.1:9003
            predicates:
              - Path=/api/v1/users/