spring:
  cloud:
    gateway:
      mvc:
        routes:
        #Public Access
          - id: public-store-service
            uri: http://192.168.160.1:9001
            predicates:
              - Path=/api/v1/public-store/
          - id: auth-admin-service
            uri: http://192.168.160.1:6001
            predicates:
              - Path=/api/v1/auth/admin/
          - id: auth-user-service
            uri: http://192.168.160.1:6002
            predicates:
              - Path=/api/v1/auth/user/
          #Admin Service
          - id: admin-service
            uri: http://192.168.160.1:9002
            predicates:
              - Path=/api/v1/admins/
          #Admin Service
          - id: user-service
            uri: http://192.168.160.1:9003
            predicates:
              - Path=/api/v1/users/
          #Folder Service
          - id: folder-service
            uri: http://192.168.160.1:9004
            predicates:
              - Path=/api/v1/folders/**
          #Folder Service
          - id: file-service
            uri: http://192.168.160.1:9005
            predicates:
              - Path=/api/v1/files/**
          #Folder Service
          - id: trash-service
            uri: http://192.168.160.1:9006
            predicates:
              - Path=/api/v1/trash/**
          #Folder Service
          - id: forgot-password-service
            uri: http://192.168.160.1:9007
            predicates:
              - Path=/api/v1/forgot-password/**